apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: smartshop
type: Opaque
stringData:  
  DB_URL: jdbc:postgresql://postgres-service:5432/smartshop_db
  DB_USER: postgres
  DB_PASSWORD: postgres123env:
        - name: POSTGRES_DB
          value: smartshop_db
        - name: POSTGRES_USER